In [2]:
import pandas as pd
import re
import os

In [3]:
STREETS_CSVS_PATH = "/home/mohamed/Mohamed/Vodafone_project/govs_street_names-20241004T002006Z-001/govs_street_names"
TXT_FILE = "street_names.txt"

In [4]:
govs_streets_csv_names = os.listdir(STREETS_CSVS_PATH)

In [5]:
all_govs_df = pd.read_csv(os.path.join(STREETS_CSVS_PATH, govs_streets_csv_names[0]))
print(all_govs_df.GOV_NAME_A.values[0])
print(len(all_govs_df))


for i in range(1, len(govs_streets_csv_names)):
    new_csv = pd.read_csv(os.path.join(STREETS_CSVS_PATH, govs_streets_csv_names[i]))
    print(new_csv.GOV_NAME_A.values[0])
    print(len(all_govs_df))
    all_govs_df = pd.concat([all_govs_df, new_csv])

all_govs_df

محافظة الغربية
7353
محافظه اسوان
7353
محافظه سوهاج
9053
محافظه الاسماعلية
9960
محافظه القليوبية
12035
محافظه اسيوط
59960
المجلس الأعلى لمدينة الاقصر
63452
محافظه القاهرة
64579
محافظه الدقهلية
98190
محافظه سوهاج
108328
محافظه سوهاج
111804
محافظة المنوفية
112503
محافظه بورسعيد
117880
محافظه الجيزه
118682
محافظه قنا
154225
محافظه دمياط
154605
محافظه جنوب سيناء
157085
محافظة الغربية
157399
محافظه الاسماعلية
161611
محافظه السويس
161699
محافظه الاسكندرية
164128
محافظه الفيوم
164812
محافظه المنيا
166786
محافظه الجيزه
171197
محافظة المنوفية
174074
محافظه البحيرة
179153
محافظه الشرقية
192752

,Unnamed: 0,GOV_NAME_A,SEC_NAME_A,SSEC_NAM_1,name,area
0,0,محافظة الغربية,مركز زفتى,كفر ميت الحارون,شارع جسر النيل,NaN
1,1,محافظة الغربية,مركز زفتى,تفهنا العزب,شارع جسر النيل,NaN
2,7,محافظة الغربية,مركز زفتى,ميت الحارون,شارع جسر النيل,NaN
3,10,محافظة الغربية,مركز زفتى,كفر ميت الحارون,طريق بنها اسطنها,NaN
4,11,محافظة الغربية,مركز زفتى,تفهنا العزب,طريق بنها اسطنها,NaN
...,...,...,...,...,...,...
18447,159674,محافظه الشرقية,قسم ثانى الزقازيق,الجامع,شارع العمده,NaN
18448,159688,محافظه الشرقية,قسم ثانى الزقازيق,الجامع,حارة الحبشي,NaN
18449,159696,محافظه الشرقية,قسم ثانى الزقازيق,الجامع,حارة سرى,NaN
18450,159710,محافظه الشرقية,قسم ثانى الزقازيق,الجامع,شارع ترعه المسلميه,NaN
18451,159713,محافظه الشرقية,قسم ثانى الزقازيق,الجامع,شارع العمده اثنان,NaN

In [6]:
x = set(all_govs_df["GOV_NAME_A"].values)

In [14]:
x = list(map(lambda x : x.replace("محافظه", "").strip(), x ))
x = list(map(lambda x : x.replace("محافظة", "").strip(), x ))

x = list(map(lambda x : x.replace("المجلس الأعلى لمدينة", "").strip(), x ))
x = list(map(lambda x : x.replace("\xa0", " ").strip(), x ))


x = x + list(map(lambda x : x.replace("ال", " ").strip(), x ))

In [15]:
x

['الجيزه',
 'قنا',
 'القاهرة',
 'اسيوط',
 'الاسكندرية',
 'دمياط',
 'كفر الشيخ',
 'الدقهلية',
 'بورسعيد',
 'الاسماعلية',
 'شمال سيناء',
 'الواديالجديد',
 'الاقصر',
 'الفيوم',
 'سوهاج',
 'البحيرة',
 'جنوبسيناء',
 'السويس',
 'الشرقية',
 'المنوفية',
 'القليوبية',
 'بنى سويف',
 'المنيا',
 'اسوان',
 'البحر الاحمر',
 'مطروح',
 'الغربية',
 'جيزه',
 'قنا',
 'قاهرة',
 'اسيوط',
 'اسكندرية',
 'دمياط',
 'كفر  شيخ',
 'دقهلية',
 'بورسعيد',
 'اسماعلية',
 'شم  سيناء',
 'وادي جديد',
 'اقصر',
 'فيوم',
 'سوهاج',
 'بحيرة',
 'جنوبسيناء',
 'سويس',
 'شرقية',
 'منوفية',
 'قليوبية',
 'بنى سويف',
 'منيا',
 'اسوان',
 'بحر  احمر',
 'مطروح',
 'غربية',
 'جيزه',
 'قنا',
 'قاهرة',
 'اسيوط',
 'اسكندرية',
 'دمياط',
 'كفر  شيخ',
 'دقهلية',
 'بورسعيد',
 'اسماعلية',
 'شم  سيناء',
 'وادي جديد',
 'اقصر',
 'فيوم',
 'سوهاج',
 'بحيرة',
 'جنوبسيناء',
 'سويس',
 'شرقية',
 'منوفية',
 'قليوبية',
 'بنى سويف',
 'منيا',
 'اسوان',
 'بحر  احمر',
 'مطروح',
 'غربية',
 'جيزه',
 'قنا',
 'قاهرة',
 'اسيوط',
 'اسكندرية',
 'دمياط',
 'كفر  شيخ',
 'دقهلية',
 'بورسعيد',
 'اسماعلية',
 'شم  سيناء',
 'وادي جديد',
 'اقصر',
 'فيوم',
 'سوهاج',
 'بحيرة',
 'جنوبسيناء',
 'سويس',
 'شرقية',
 'منوفية',
 'قليوبية',
 'بنى سويف',
 'منيا',
 'اسوان',
 'بحر  احمر',
 'مطروح',
 'غربية',
 'جيزه',
 'قنا',
 'قاهرة',
 'اسيوط',
 'اسكندرية',
 'دمياط',
 'كفر  شيخ',
 'دقهلية',
 'بورسعيد',
 'اسماعلية',
 'شم  سيناء',
 'وادي جديد',
 'اقصر',
 'فيوم',
 'سوهاج',
 'بحيرة',
 'جنوبسيناء',
 'سويس',
 'شرقية',
 'منوفية',
 'قليوبية',
 'بنى سويف',
 'منيا',
 'اسوان',
 'بحر  احمر',
 'مطروح',
 'غربية',
 'جيزه',
 'قنا',
 'قاهرة',
 'اسيوط',
 'اسكندرية',
 'دمياط',
 'كفر  شيخ',
 'دقهلية',
 'بورسعيد',
 'اسماعلية',
 'شم  سيناء',
 'وادي جديد',
 'اقصر',
 'فيوم',
 'سوهاج',
 'بحيرة',
 'جنوبسيناء',
 'سويس',
 'شرقية',
 'منوفية',
 'قليوبية',
 'بنى سويف',
 'منيا',
 'اسوان',
 'بحر  احمر',
 'مطروح',
 'غربية',
 'جيزه',
 'قنا',
 'قاهرة',
 'اسيوط',
 'اسكندرية',
 'دمياط',
 'كفر  شيخ',
 'دقهلية',
 'بورسعيد',
 'اسماعلية',
 'شم  سيناء',
 'وادي جديد',
 'اقصر',
 'فيوم',
 'سوهاج',
 'بحيرة',
 'جنوبسيناء',
 'سويس',
 'شرقية',
 'منوفية',
 'قليوبية',
 'بنى سويف',
 'منيا',
 'اسوان',
 'بحر  احمر',
 'مطروح',
 'غربية',
 'جيزه',
 'قنا',
 'قاهرة',
 'اسيوط',
 'اسكندرية',
 'دمياط',
 'كفر  شيخ',
 'دقهلية',
 'بورسعيد',
 'اسماعلية',
 'شم  سيناء',
 'وادي جديد',
 'اقصر',
 'فيوم',
 'سوهاج',
 'بحيرة',
 'جنوبسيناء',
 'سويس',
 'شرقية',
 'منوفية',
 'قليوبية',
 'بنى سويف',
 'منيا',
 'اسوان',
 'بحر  احمر',
 'مطروح',
 'غربية']

In [5]:
all_govs_df = all_govs_df.drop(columns=["Unnamed: 0", "area"])
# First fixing
# Remove all punctuation

def remove_punctuation(x):
  x["name"] = re.sub(r'[^\w\s]','',str(x["name"]))
  x["SSEC_NAM_1"] = re.sub(r'[^\w\s]','',str(x["SSEC_NAM_1"]))
  x["SEC_NAME_A"] = re.sub(r'[^\w\s]','',str(x["SEC_NAME_A"]))
  x["GOV_NAME_A"] = re.sub(r'[^\w\s]','',str(x["GOV_NAME_A"]))

  # Remove محافظة
  x["GOV_NAME_A"] = x["GOV_NAME_A"].replace("محافظه", "").strip()
  x["GOV_NAME_A"] = x["GOV_NAME_A"].replace("محافظة", "").strip()
  x["GOV_NAME_A"] = x["GOV_NAME_A"].replace("المجلس الأعلى لمدينة", "").strip()


  return x

all_govs_df = all_govs_df.apply(remove_punctuation, axis=1)

In [6]:
all_govs_df.to_csv("govs_streets.csv")

In [7]:
PREFIX_WORDS = ["اول", "اخر", "أول", "أخر", "آخر", "بداية", "نهاية", "منتصف", "مدخل", "خلف", "جانب", "جنب", "ورا", "قبل", "بعد", "في", "تقاطع", "مقابل", "أدام", "امام", "قدام", "فوق", "أسفل", "محاذاة", "عند", "وسط", "على", "مجاور", "خلف", "بين", "قبالة", "تقاطع", "جنوب", "شمال", "محيط", "مدخل", "قبال", "ابال", "إبال", "مع" ]

In [8]:
import codecs

In [9]:
# write to txt file
import random


def concat_names(x):
    x["all_name"] = " ".join([random.choice(PREFIX_WORDS), x["name"], x["SSEC_NAM_1"], x["SEC_NAME_A"], x["GOV_NAME_A"]+"\n"])
    return x

names = all_govs_df.apply(concat_names, axis=1)
with codecs.open(TXT_FILE, "w", encoding='utf-8') as f:
    f.writelines(list(names["all_name"].values))

# write to txt file قاهرة مش القاهرة
def concat_names(x):
    x["all_name"] = " ".join([random.choice(PREFIX_WORDS), x["name"], x["SSEC_NAM_1"], x["SEC_NAME_A"], x["GOV_NAME_A"].replace("ال", "").strip()+"\n"])
    return x

names = all_govs_df.apply(concat_names, axis=1)

with codecs.open(TXT_FILE, "a+", encoding='utf-8') as f:
    f.writelines(list(names["all_name"].values))

In [10]:
# Remove common words (قسم, مركز)

def remove_common(x):
    x["SEC_NAME_A"] = x["SEC_NAME_A"].replace("مركز", "").strip()
    x["SEC_NAME_A"] = x["SEC_NAME_A"].replace("قسم", "").strip()
    x["SEC_NAME_A"] = x["SEC_NAME_A"].replace("مدينة", "").strip()

    x["SSEC_NAM_1"] = x["SSEC_NAM_1"].replace("مدينة", "").strip()
    x["SSEC_NAM_1"] = x["SSEC_NAM_1"].replace("شياخة", "").strip()

    return x

all_govs_df = all_govs_df.apply(concat_names, axis=1)

In [11]:
# write to txt file
def concat_names(x):
    x["all_name"] = " ".join([random.choice(PREFIX_WORDS), x["name"], x["SSEC_NAM_1"], x["SEC_NAME_A"], x["GOV_NAME_A"]+"\n"])
    return x

names = all_govs_df.apply(concat_names, axis=1)
names
with codecs.open(TXT_FILE, "a+", encoding='utf-8') as f:
    f.writelines(list(names["all_name"].values))


# write to txt file قاهرة مش القاهرة
def concat_names(x):
    x["all_name"] = " ".join([random.choice(PREFIX_WORDS), x["name"], x["SSEC_NAM_1"], x["SEC_NAME_A"], x["GOV_NAME_A"].replace("ال", "").strip()+"\n"])
    return x

names = all_govs_df.apply(concat_names, axis=1)
names
with codecs.open(TXT_FILE, "a+", encoding='utf-8') as f:
    f.writelines(list(names["all_name"].values))

In [1]:
import pandas as pd

In [11]:
streets = pd.read_csv("/home/mohamed/Mohamed/Vodafone_project/projects/app/scripts/govs_streets.csv")

In [12]:
streets = streets.sample(frac=1)

In [13]:
streets = streets.iloc[:5000,:]

In [20]:
streets = streets.drop(columns=["index"])

In [18]:
streets.reset_index(inplace=True)

In [21]:
streets

,GOV_NAME_A,SEC_NAME_A,SSEC_NAM_1,name
0,الجيزه,ابوالنمرس,ترسا,شارع سكر الابار
1,القاهرة,قسم عين شمس,شياخة الزهراء و مساكن الحلمية,حارة متولي الهواري
2,القاهرة,قسم المرج,شياخة المرج البحرية,حارة عبد المجيد محمد
3,القاهرة,قسم السلام,شياخة السلام الغربية,شارع الشيخ كامل
4,كفر الشيخ,قسم دسوق,مدينة دسوق,شارع اثنان
...,...,...,...,...
4995,الشرقية,قسم فاقوس,مدينة فاقوس,شارع اسماعيل مصطفى
4996,الشرقية,مركز ابوكبير,مدينة ابوكبير,شارع الرماس
4997,اسيوط,قسم ثان اسيوط,الحمراء الثانية,شارع تقسيم البترول
4998,الشرقية,مركز ديرب نجم,مدينة ديرب نجم,طريق عزبة رضوان
4999,دمياط,دمياط,شط محب والسيالة,شارع ابو العباس واحد

In [22]:
streets.to_csv("small_streets.csv")

In [25]:
import pandas as pd
streets = pd.read_csv("small_streets.csv")

def concat_names(x):
    x["all_name"] = " ".join([x["name"], x["SSEC_NAM_1"], x["SEC_NAME_A"], x["GOV_NAME_A"].replace("ال", "").strip()])
    return x

streets_with_concated_names = streets.apply(concat_names, axis=1)
print(list(streets_with_concated_names["all_name"].values))

['شارع سكر الابار ترسا ابوالنمرس جيزه', 'حارة متولي الهواري شياخة الزهراء و مساكن الحلمية قسم عين شمس قاهرة', 'حارة عبد المجيد محمد شياخة المرج البحرية قسم المرج قاهرة', 'شارع الشيخ كامل شياخة السلام الغربية قسم السلام قاهرة', 'شارع اثنان مدينة دسوق قسم دسوق كفر شيخ', 'شارع متفرع من شارع ابو العلا مسطرد قسم ثان شبرا الخيمه قليوبية', 'شارع غريب اولاد العدوى مركز فاقوس شرقية', 'شارع ربيع جود شياخة  مساكن الاميرية الشمالية قسم الزيتون قاهرة', 'شارع محمد ذكى القلج مركز الخانكه قليوبية', 'حارة عبد الحميد دسوقي شياخة  مساكن الاميرية الشمالية قسم الزيتون قاهرة', 'حارة الحاج عبد الباسط شياخة المرج البحرية قسم المرج قاهرة', 'شارع على الجارم مدينه العبور قسم العبور قليوبية', 'شارع على فرج منشأة البكارى قسم الاهرام جيزه', 'شارع السعاده شياخة اثر النبى قسم مصر القديمه قاهرة', 'شارع مئتان و سبعة و خمسون شياخه البساتين الشرقية قسم البساتين قاهرة', 'شارع السلام شياخة المحاجر قسم منشاه ناصر قاهرة', 'شارع ثلاثة مدينة ادكو ادكو بحيرة', 'شارع طراد النيل واحد و عشرون مدينة الواسطى الواسطى بنى سويف', 'شارع فؤاد عبد الحكيم شياخة الزاوية الحمراء مساكن قسم الزاويه الحمراء قاهرة', 'شارع الصيفى كفر الحارث مركز القناطر الخيريه قليوبية', 'شارع فؤاد السيد على المنشأة\xa0الصغري مركز كفر شكر قليوبية', 'شارع الايمان شياخة طلمبات عين شمس قسم عين شمس قاهرة', 'شارع ستة و أربعون الشياخة الرابعه قسم ثان 6 اكتوبر جيزه', 'شارع خلف الساحة قسم ثالث قسم المنيا منيا', 'حارة ابو على مدينة الخصوص قسم الخصوص قليوبية', 'شارع المحكمة المكس قسم الدخيله اسكندرية', 'شارع أحد عشر العجمى البحرية قسم الدخيله اسكندرية', 'شارع احمد عبد المولى النطاط شنبارى اوسيم جيزه', 'شارع الرواسيل جزيره الخزندارية طهطا سوهاج', 'حارة هاشم الدمناوي مازن قسم اول سوهاج سوهاج', 'شارع جمال حسن شياخه البساتين الشرقية قسم البساتين قاهرة', 'شارع متفرع من شارع محمود زغلول الجبل الأصفر مركز الخانكه قليوبية', 'شارع جابر حمدان مرسى شياخة قسم ثالث قسم الاربعين سويس', 'طريق قرية كفر دبوس مدينه الابراهيميه الاحسانية مركز ههيا شرقية', 'حارة النظامى مدينة شبرا الخيمة قسم اول شبرا الخيمه قليوبية', 'شارع محمد خطاب العمرانية الغربية قسم العمرانيه جيزه', 'شارع مستودع الرمل كفر\xa0مويس مركز بنها قليوبية', 'شارع فرج ابو زهره مدينة بلقاس بلقاس دقهلية', 'شارع مسجد الرحمن الرقة الغربية العياط جيزه', 'شارع سيد محمد عبده سرياقوس مركز الخانكه قليوبية', 'شارع الإمام احمد بن حنبل الميمونة مركز منيا القمح شرقية', 'شارع السيد حسن الزيدية اوسيم جيزه', 'شارع طارق الكمار طنان مركز قليوب قليوبية', 'زقاق الطوبى شياخة العليمى الفرنساوى سابقا قسم بولاق قاهرة', 'كوبرى خمسة عشر مايو شياخة السندبيس قسم بولاق قاهرة', 'شارع ترعه الجلاد شياخة الزاوية الحمراء مساكن قسم الزاويه الحمراء قاهرة', 'شارع هيثم شياخة المرج البحرية قسم المرج قاهرة', 'حارة ابراهيم حلمى مدينة فاقوس قسم فاقوس شرقية', 'شارع عبد المنعم حسن تاج الدول قسم امبابه جيزه', 'شارع جسر الرياح التوفيقى المنشية قسم بنها قليوبية', 'شارع نبيل الشرقاوي شياخة قسم رابع قسم الاربعين سويس', 'شارع طابا اثنان قسم اول ميت طلخا قسم اول المنصورة دقهلية', 'شارع المنيا مدينة ديروط ديروط اسيوط', 'شارع ملاك شياخة العصارة الجديدة قسم السلام قاهرة', 'شارع جمال مره جودة حسن حبيب قسم شبين الكوم منوفية', 'شارع كمال عمر مدينه العبور قسم العبور قليوبية', 'شارع عاشور شياخة القادرية قسم الخليفه قاهرة', 'شارع ابو شيبه ناهيا كرداسه جيزه', 'حارة بيومى ابراهيم شياخة الزيتون الغربية قسم الزيتون قاهرة', 'شارع الحاج عبد الباسط كفرغطاطى قسم الاهرام جيزه', 'شارع عبد العال صبحي شياخة الزاوية الحمراء البلد قسم الشرابيه قاهرة', 'شارع بدوى مدينة بركة السبع مركز بركه السبع منوفية', 'شارع طارق بن زياد عوض الزواوى قسم كفر الشيخ كفر شيخ', 'شارع سكة الناصر حارة اولى قسم الجيزه جيزه', 'شارع السكة الجديدة الحارة\xa0الواسعة\xa0والتخشيبة اللبان اسكندرية', 'شارع الحاج عبد العزيز الحسانين مركز امبابة جيزه', 'شارع احمد سالم شياخة العزب قسم المطريه قاهرة', 'شارع الحضانة مدينة سرس الليانة قسم مدينه سرس الليانة منوفية', 'كوبري ستة أكتوبر العجوزة قسم العجوزه جيزه', 'شارع مسجد الجدال مدينة كرداسة كرداسه جيزه', 'شارع عرابي شياخة القللى قسم الازبكيه قاهرة', 'شارع الفاروق عمر بن الخطاب مدينة الوراق قسم الوراق جيزه', 'شارع مسجد الإخلاص بنى حسن مركز اولاد صقر شرقية', 'طريق عزبة الحجازيه الملكيين البحرية مركز الحسينية شرقية', 'شارع الموقف مدينه جمصة قسم جمصة دقهلية', 'حارة خمسة عشر صفط اللبن كرداسه جيزه', 'شارع مسجد اولى العزم شلقان مركز القناطر الخيريه قليوبية', 'شارع مسجد الايمان الملحقات قسم كفر الشيخ كفر شيخ', 'حارة مطر عبد العال شياخة حلوان البلد قسم حلوان قاهرة', 'شارع السكة الحديد ابنود مركز قنا قنا', 'شارع مساكن ري المعلمين الجزيرة قبلى قسم بنى سويف بنى سويف', 'شارع كامل ابو الهنا بهتيم قسم ثان شبرا الخيمه قليوبية', 'شارع صلاح الدين الايوبى المهاجرين قسم المنتزة اسكندرية', 'طريق النوباريه الحمام النهضة قسم برج العرب اسكندرية', 'شارع صلاح سالم السوالم طهطا سوهاج', 'شارع راجح السوهاجى الجبل الأصفر مركز الخانكه قليوبية', 'شارع غازي السعرانية قسم كفرالدوار بحيرة', 'شارع مرعي سلمى باسوس مركز القناطر الخيريه قليوبية', 'شارع مصطفى حبيب التحرير قسم أول المحلة الكبرى غربية', 'شارع رابعه العدويه بنى مجدول كرداسه جيزه', 'شارع الحسين شياخة كفر الشرفا قسم المرج قاهرة', 'شارع خيري شياخة منشية البكرى قسم مصر الجديده قاهرة', 'شارع سعد سكنيدة قسم دمنهور بحيرة', 'طريق عزبة ابو عامر محمود عبد الصمد مركز امبابة جيزه', 'شارع سعيد الملجأ قسم ثان طنطا غربية', 'شارع ابن طولون مدينة طوخ مركز طوخ قليوبية', 'شارع حوش قدم شياخة حارة الروم قسم الدرب الاحمر قاهرة', 'شارع فتحي نعيم شبرا قسم دمنهور بحيرة', 'شارع شعبان طه السيد القلج مركز الخانكه قليوبية', 'شارع سيد عطا مدينة ابوكبير مركز ابوكبير شرقية', 'شارع موريس الضبع نزلة السمان قسم الاهرام جيزه', 'كوبرى بحر البقر منشأة مصطفى خليل مركز الحسينية شرقية', 'طريق مصرف القصاصين الابراهيمية مركز دسوق كفر شيخ', 'طريق بنها اسطنها كفر\xa0ميت\xa0الحارون مركز زفتى غربية', 'شارع مسجد الرحمن شياخة عزبة الهجانة قسم اول مدينه نصر قاهرة', 'شارع اثنا عشر مدينة ميت سلسيل ميت سلسيل دقهلية', 'شارع على سقيطه المنيرة مركز القناطر الخيريه قليوبية', 'حارة أحد عشر شياخة حلوان البلد قسم حلوان قاهرة', 'عطفه البهلول قسم ثان الحوار قسم اول المنصورة دقهلية', 'شارع شحته جعفر كفر\xa0مويس مركز بنها قليوبية', 'شارع المهندس مدحت منشأة البكارى قسم الاهرام جيزه', 'شارع محمد عبد الله القشيش مركز شبين القناطر قليوبية', 'شارع الحاج محمد محمود حنفى المعتمدية كرداسه جيزه', 'شارع حمدى العدوى الحكر قسم ثان الاسماعيلية اسماعلية', 'شارع محمد احمد عطوه كفر\xa0الشهاوي\xa0خاطر مركز كفر شكر قليوبية', 'شارع العطار شياخة الشرابية قسم الشرابيه قاهرة', 'شارع الهدي الحسينية قسم اول الزقازيق شرقية', 'شارع احمد غيار صنافير مركز قليوب قليوبية', 'شارع خمسة و عشرون العصافرة المطرية دقهلية', 'شارع فاروق الفوري شياخة المرج البحرية قسم المرج قاهرة', 'حارة سعد يوسف منشأة البكارى قسم الاهرام جيزه', 'شارع العزيز بالله يوسف شياخة عزب العرب قسم ثان مدينه نصر قاهرة', 'طريق تل راك زور ابو الليل مركز اولاد صقر شرقية', 'شارع الجمعيه الزراعيه بشتيل قسم الوراق جيزه', 'شارع شرق مزغونة مزغونة البدرشين جيزه', 'شارع احمد بهاء نصار مدينة قها قسم قها قليوبية', 'حارة الرفاعى النحال قسم اول الزقازيق شرقية', 'حارة الربيع شياخه البساتين الشرقية قسم البساتين قاهرة', 'شارع ابراهيم زيدان الجبل الأصفر مركز الخانكه قليوبية', 'شارع ماهر مكرم سرياقوس مركز الخانكه قليوبية', 'شارع حكيم باشا البوليس المحروسة قسم ثان الرمل اسكندرية', 'شارع ابراج الامل شياخه بنها قسم بنها قليوبية', 'حارة مسعد أبو علي شياخة حلوان البلد قسم حلوان قاهرة', 'حارة سيدى بدران بشتيل قسم الوراق جيزه', 'حارة حامد محمد شياخة عزب العرب قسم ثان مدينه نصر قاهرة', 'شارع الرحمن المرماح بحرى قسم بنى سويف بنى سويف', 'شارع محمود عبد الجواد مدينه بيلا بيلا كفر شيخ', 'طريق اسيوط قنا الزراعى الغريب ساحل سليم اسيوط', 'شارع فوزى عزمى اولى الهرم قسم العمرانيه جيزه', 'شارع معوض يوسف مدينه بيلا بيلا كفر شيخ', 'حارة محيي الدين حارة رابعة قسم الجيزه جيزه', 'زقاق العريان مدينه ناصر ناصر بنى سويف', 'شارع مدرسه ثروت مدينة ابوالمطامير ابوالمطامير بحيرة', 'شارع سكر شياخة عرب الحصن قسم المطريه قاهرة', 'شارع فتحي عبد الفتاح بهتيم قسم ثان شبرا الخيمه قليوبية', 'شارع السقا بردلة قسم كفرالدوار بحيرة', 'شارع خمسة عشر مدينة منية النصر منيه النصر دقهلية', 'شارع محمد طه نقباس مركز بنها قليوبية', 'حارة اسماعيل الحلوانى بهتيم قسم ثان شبرا الخيمه قليوبية', 'طريق الاصلاح الزراعى كفر\xa0منصور مركز كفر شكر قليوبية', 'شارع عزبة بركه حوض نجيح مركز ههيا شرقية', 'شارع السيد المزين السلخانه قسم ثان طنطا غربية', 'شارع العقباوى محمود عبد الصمد مركز امبابة جيزه', 'نفق تحيا مصر منشأة الشهداء قسم ثان الاسماعيلية اسماعلية', 'شارع محمد موسى كفر\xa0عليم مركز القناطر الخيريه قليوبية', 'شارع لبنه مدينة البدرشين البدرشين جيزه', 'شارع رضوان شياخة عرب اليسار قسم الخليفه قاهرة', 'ميدان الكيت كات ميت كردك قسم امبابه جيزه', 'شارع صالح خليل الزقازيق البحرية قسم ثانى الزقازيق شرقية', 'شارع المعهد الازهرى ميت العز مركز فاقوس شرقية', 'شارع محمد مبارك قسم كفر البدماص قسم ثان المنصورة دقهلية', 'شارع الجهاد مدينة فارسكور فارسكور دمياط', 'شارع الشيخ احمد ابو مسافر شياخة المرج البحرية قسم المرج قاهرة', 'شارع سبعة و أربعون مدينة اولاد صقر مركز اولاد صقر شرقية', 'شارع حسين جمعه كوبرى المحطه قسم أول طنطا غربية', 'شارع الشعراوى سندوب وكفر المناصرة قسم اول المنصورة دقهلية', 'شارع سيد المشد ابو سنه مركز قليوب قليوبية', 'شارع حسن سليمان شياخه البساتين الغربية قسم البساتين قاهرة', 'شارع احمد رمضان منشأة\xa0الكرام مركز شبين القناطر قليوبية', 'شارع مدخل كفر الدوار مدينة كفرالدوار قسم كفرالدوار بحيرة', 'شارع الحريه نبتيت مركز مشتول السوق شرقية', 'شارع على و على نوي مركز شبين القناطر قليوبية', 'شارع متفرع من شارع البكباشى ترسا ابوالنمرس جيزه', 'حارة المتولي شياخة السويس ثان قسم السويس سويس', 'شارع ثمانية عشر جديلة قسم ثان المنصورة دقهلية', 'شارع النمر مسطرد قسم ثان شبرا الخيمه قليوبية', 'درب الحسينيه قسم ثالث قسم الفيوم فيوم', 'شارع مسجد الصوارفه مدينة التل الكبير مركز التل الكبير اسماعلية', 'حارة الشيخ شياخة عزبة الهجانة قسم اول مدينه نصر قاهرة', 'شارع مائة و خمسة مدينة راس البر راس البر دمياط', 'شارع متفرع من شارع سعيد العربى عرب العيايدة مركز الخانكه قليوبية', 'شارع منصور محمود جزيرة\xa0بلي مركز بنها قليوبية', 'حارة فلسطين نزلة البطران قسم الاهرام جيزه', 'شارع ناصر الصعيدي منشأة البكارى قسم الاهرام جيزه', 'شارع التحرير مدينة ايتاى البارود ايتاى البارود بحيرة', 'شارع بورسعيد مسهلة مركز السنطه غربية', 'شارع محمود جمعه شياخة السلام الغربية قسم السلام قاهرة', 'شارع مصطفى احمد المنيرة مركز القناطر الخيريه قليوبية', 'شارع اولاد خلاف مدينة الخصوص قسم الخصوص قليوبية', 'شارع الرياضة شياخة المنطقة الاولى قسم اول مدينه نصر قاهرة', 'حارة خلف غبريال شياخة الزاوية الحمراء مساكن قسم الزاويه الحمراء قاهرة', 'شارع النصر مدينة اهناسيا اهناسيا بنى سويف', 'شارع الكمال مدينة الخصوص قسم الخصوص قليوبية', 'حارة جابر قسم ثان قسم ملوى منيا', 'شارع مسجد قباء كفر\xa0حمزة مركز الخانكه قليوبية', 'طريق ادفينا المحمودية منية السعيد المحموديه بحيرة', 'شارع الجمال باسوس مركز القناطر الخيريه قليوبية', 'حارة واحد السنبلاوين مركز السنبلاوين دقهلية', 'شارع الانصار شياخة العصارة الجديدة قسم السلام قاهرة', 'شارع ابو طلبه شياخة العصارة الجديدة قسم السلام قاهرة', 'شارع القدس مدينة اوسيم اوسيم جيزه', 'شارع دكتور شهاب قسم اول قسم الفيوم فيوم', 'حارة طه الترزى جزيرة ميت عقبة قسم العجوزه جيزه', 'شارع عثمان تمام العمرانية الشرقية قسم العمرانيه جيزه', 'شارع حليمه حسن مدينة زفتى مركز زفتى غربية', 'حارة الشفره شياخة قسم رابع قسم الاربعين سويس', 'شارع خلف مدرسه السادات شياخة ناصر قسم أول المحلة الكبرى غربية', 'شارع محمود عبد الغنى الخرقانية مركز القناطر الخيريه قليوبية', 'شارع جسر مصرف مغاغه مدينة الفشن الفشن بنى سويف', 'شارع سوريا مدينة كوم حمادة كوم حماده بحيرة', 'شارع عبد الحي مدينة فاقوس قسم فاقوس شرقية', 'الطريق الساحلى الدولى ام الرضا الجديدة كفر سعد دمياط', 'شارع عاصم الكفره الشرقية قسم ثان طنطا غربية', 'شارع البحيره مدينة المطرية المطرية دقهلية', 'شارع الشعراوى مدينة ميت غمرتشمل دقادوس قسم ميت غمر دقهلية', 'شارع المسجد الاحمدى الكبير العلوية مركز الزقازيق شرقية', 'شارع السيد الشرقاوي على أغا قسم ثان طنطا غربية', 'شارع خمسمائة و واحد و تسعون سيدى بشر قبلى قسم المنتزة اسكندرية', 'طريق عزبة موسى شوقى النعامنة مركز منيا القمح شرقية', 'شارع سيف الدين قطز قسم سابع البحر الصغير قسم ثان المنصورة دقهلية', 'شارع الجنينه جزيرة\xa0الدهب قسم الجيزه جيزه', 'شارع مصطفى حجازي مدينة كرداسة كرداسه جيزه', 'شارع الحسن مدينة نبروة نبروه دقهلية', 'شارع مسجد ابراهيم الدسوقي فرسيس مركز بنها قليوبية', 'شارع سبعمائة و أربعة و ثلاثون الشياخة الرابعه قسم ثان 6 اكتوبر جيزه', 'شارع على حليمه السنبلاوين مركز السنبلاوين دقهلية', 'حارة الاهواني مدينة سرس الليانة قسم مدينه سرس الليانة منوفية', 'شارع الباروديه القبليه قسم ثان قسم الفيوم فيوم', 'زقاق المتوكل مدينه ناصر ناصر بنى سويف', 'شارع بلال الشرقي شياخة العزب قسم الشرابيه قاهرة', 'شارع محمد مختار القصعى قبلى قسم اول الرمل اسكندرية', 'شارع عبد الستار خضر بطا مركز بنها قليوبية', 'شارع عبده الطويل الحريرى قسم اول الزقازيق شرقية', 'شارع ابو النصر الصيادين الجمرك اسكندرية', 'شارع القادسية كفر محمد حسين مركز الزقازيق شرقية', 'شارع محمد عباس ناهيا كرداسه جيزه', 'شارع الارناؤوطي شياخة الزيتون القبلية قسم الزيتون قاهرة', 'حارة الصعايده مدينة الوراق قسم الوراق جيزه', 'حارة الشوافعه كفر\xa0شبين مركز شبين القناطر قليوبية', 'شارع المصانع الدقى قسم الدقى جيزه', 'الطريق الدائري الإقليمي منشأة\xa0مسجد\xa0الخضر مركز الباجور منوفية', 'شارع محمد فريد التمساح قسم اول الاسماعيلية اسماعلية', 'طريق مجول بلتان بلتان مركز طوخ قليوبية', 'ميدان مجلس مدينه دراو مدينه دراو مركز دراو اسوان', 'حارة القاضي مدينة الواسطى الواسطى بنى سويف', 'شارع صابر البنا شوبك بسطة مركز الزقازيق شرقية', 'حارة حسن عبد المقصود مدينة كرداسة كرداسه جيزه', 'شارع مسجد نور الاسلام بلقس مركز قليوب قليوبية', 'شارع دكتور عزيز صدقى مسطرد قسم ثان شبرا الخيمه قليوبية', 'شارع الحاج سلامه دنا الجديدة قسم اول الرمل اسكندرية', 'شارع ياسين العارف الكبش قسم ثان سوهاج سوهاج', 'حارة سيد محمود الجبل الأصفر مركز الخانكه قليوبية', 'حارة الحسانات العامود مينا البصل اسكندرية', 'شارع خالد سعيد بهتيم قسم ثان شبرا الخيمه قليوبية', 'شارع واحد حارة\xa0الفراهدة اللبان اسكندرية', 'طريق ستة و ثلاثون الحربي الظهير الصحراوى العاشر من رمضان الظهير الصحراوى العاشر من رمضان شرقية', 'شارع السيد نصر مدينة ابوحماد مركز ابوحماد شرقية', 'شارع رشاد هيكل شياخة بركة الحاج قسم المرج قاهرة', 'ممر المكباتي المسلة\xa0شرق العطارين اسكندرية', 'شارع المدرسه الناصرية  المعرقب سابقا العياط جيزه', 'شارع عبد الله السوداني شياخة الزاوية الحمراء مساكن قسم الزاويه الحمراء قاهرة', 'شارع صلاح الدين منشاة دهشور البدرشين جيزه', 'شارع المطحن بلقس مركز قليوب قليوبية', 'حارة محمد هاشم شياخة الكبش قسم السيده زينب قاهرة', 'شارع مدرسة طلائع الفاروق مدينة الخصوص قسم الخصوص قليوبية', 'شارع متفرع من شارع مسجد الهدايه واحد مدينة الخانكة مركز الخانكه قليوبية', 'شارع محمود عبد العال شياخة المرج القبلية قسم المرج قاهرة', 'شارع تسعة نفيا مركز طنطا غربية', 'شارع مسجد مجدي ابو لامون شنبارى اوسيم جيزه', 'شارع اسامه غازي شياخة عين شمس الغربية قسم المطريه قاهرة', 'شارع خلف المضيفه باسوس مركز القناطر الخيريه قليوبية', 'شارع سبعة مدينة التحرير قسم امبابه جيزه', 'شارع مصطفى رياض شياخة المنطقة الاولى قسم اول مدينه نصر قاهرة', 'شارع ثلاثة المصلوب الواسطى بنى سويف', 'حارة مسجد الرحمن شياخة المعصرة البلد قسم حلوان قاهرة', 'شارع مدرسه سيناء بهتيم قسم ثان شبرا الخيمه قليوبية', 'طريق قشا المنير مركز مشتول السوق شرقية', 'شارع حسين ابراهيم نوي مركز شبين القناطر قليوبية', 'شارع خمسة عشر منشأة أباظة قسم اول الزقازيق شرقية', 'شارع طراد النيل القضابى الفشن بنى سويف', 'شارع امين يسري شياخة عزبة النخل الشرقية قسم المرج قاهرة', 'شارع احمد أبو زيد مدينة الوراق قسم الوراق جيزه', 'طريق جزيره بلى سري مركز طوخ قليوبية', 'شارع صقر عبد الرؤوف شياخة بركة النصر قسم السلام قاهرة', 'حارة الحلوانى زعربانه و الحمام قسم ثان الرمل اسكندرية', 'شارع السيد عفيفى سري مركز طوخ قليوبية', 'شارع عزام مدينة القناطر الخيرية مركز القناطر الخيريه قليوبية', 'شارع مصطفى كامل مدينة القنطرة غرب مركز القنطره اسماعلية', 'شارع سعد ابو سعيد شياخة مدينة الصلب قسم التبين قاهرة', 'طريق المحمودية دمنهور سنابادة المحموديه بحيرة', 'شارع المناشي التوفيقيه الرهاوى مركز امبابة جيزه', 'عطفه عطيه عامر شياخة المطرية البحرية قسم المطريه قاهرة', 'شارع فؤاد شاهين مدينة بلبيس مركز بلبيس شرقية', 'شارع الجيش مدينة الفشن الفشن بنى سويف', 'شارع العمده الحسانين مركز امبابة جيزه', 'شارع العقاد واحد الحدادى وعزبها سيدى سالم كفر شيخ', 'شارع الترعه ناي مركز قليوب قليوبية', 'شارع ابو اسماعيل مدينة منيا القمح مركز منيا القمح شرقية', 'شارع مصرف بلبيس عرب العيايدة مركز الخانكه قليوبية', 'شارع مكتب البريد شياخة المحاجر قسم منشاه ناصر قاهرة', 'حارة الرسول مدينة فوه فوه كفر شيخ', 'شارع سليمان حارة اولى قسم الجيزه جيزه', 'حارة سمير بريش نزلة السمان قسم الاهرام جيزه', 'شارع النصر سندوب وكفر المناصرة قسم اول المنصورة دقهلية', 'كوبري الزاويه شياخة الوايلى الكبير غرب قسم حدائق القبه قاهرة', 'شارع ترعه بشتيل المنيرة قسم امبابه جيزه', 'شارع واحد و ستون شياخة قسم رابع قسم الاربعين سويس', 'شارع واحد و خمسون مدينة نصر النوبة نصر اسوان', 'شارع ابن سعيد زعربانه و الحمام قسم ثان الرمل اسكندرية', 'شارع مسجد فجر الاسلام شياخة كفر الباشا قسم المرج قاهرة', 'شارع مائة و واحد و ستون شياخة حلوان البحرية قسم حلوان قاهرة', 'شارع عادل عواد زيدان بهتيم قسم ثان شبرا الخيمه قليوبية', 'شارع محمد علي شياخة البستان قسم مصر الجديده قاهرة', 'شارع السماد بحرى ابوالريش قبلى مركز اسوان اسوان', 'شارع الكنيسه الانجيليه الخامسة قسم اول اسيوط اسيوط', 'طريق عزبة الجبل أكياد\xa0دجوي مركز طوخ قليوبية', 'شارع محمد صابر نزلة بهجت قسم بولاق الدكرور جيزه', 'شارع محمد منير شياخة الامامين قسم الخليفه قاهرة', 'شارع الخضرى شياخة الساحة قسم عابدين قاهرة', 'شارع على عبد الودود مدينة الوراق قسم الوراق جيزه', 'شارع السوق مدينة العدوة العدوه منيا', 'شارع أربعة عشر سكنيدة قسم دمنهور بحيرة', 'شارع ابراهيم ياسين ابو رواش كرداسه جيزه', 'شارع المالك مدينة الخانكة مركز الخانكه قليوبية', 'طريق نجع حمادى سوهاج السمطا البلينا سوهاج', 'شارع مسجد النور المندرة قبلى قسم المنتزة اسكندرية', 'شارع محمد هيكل الخرقانية مركز القناطر الخيريه قليوبية', 'شارع صلاح حسين قلما مركز قليوب قليوبية', 'شارع ياسر جلال الخرقانية مركز القناطر الخيريه قليوبية', 'شارع عبد العال ابراهيم السنبلاوين مركز السنبلاوين دقهلية', 'شارع احمد زينهم سندوة مركز الخانكه قليوبية', 'شارع محمد عبد العزيز الطويل سندانهور مركز بنها قليوبية', 'شارع مسجد الرزاق كفر حماد مركز كفر صقر شرقية', 'شارع ابو شريف القلج مركز الخانكه قليوبية', 'شارع سلامه عطوه ميت\xa0راضي مركز بنها قليوبية', 'شارع مراد العناينة دمياط دمياط', 'طريق حوض الجمل ميت العطار مركز بنها قليوبية', 'شارع ابو بكر الصديق مدينة البياضيه مركز الاقصر اقصر', 'شارع محمد انيس شياخة الجولف قسم اول مدينه نصر قاهرة', 'شارع اولاد قدح عرب الغديري مركز طوخ قليوبية', 'شارع مسجد ال سليمان ميت ابوعربى مركز الزقازيق شرقية', 'طريق سقارة السياحي العزيزية البدرشين جيزه', 'شارع الهاشميه مدينة القرين قسم القرين شرقية', 'حارة مصطفى سيد شياخة حكر التبين قسم التبين قاهرة', 'شارع جمال حنفى محمود المنية مركز الخانكه قليوبية', 'حارة حولقوم الجمال شياخة الغورية قسم الدرب الاحمر قاهرة', 'شارع بكر الزناتى السنبلاوين مركز السنبلاوين دقهلية', 'شارع الحاج امين عثمان أرض اللواء كرداسه جيزه', 'شارع امين فكري شياخة الترعة البولاقية قسم شبرا قاهرة', 'شارع مسجد عزبة نبيه الكتيبة مركز بلبيس شرقية', 'شارع حمدى مدينة المطرية المطرية دقهلية', 'حارة الكرانى أبو\xa0زعبل مركز الخانكه قليوبية', 'شارع رشدى كفر المصلحية قسم شبين الكوم منوفية', 'شارع مسجد الذكر الحكيم كفرة نصار قسم الاهرام جيزه', 'طريق بحطيط كفر عباد الحلمية مركز ابوحماد شرقية', 'شارع مدرسه الايمان الخاصه زاوية نابت اوسيم جيزه', 'شارع مسجد الرحمه ارض الجمعية  ستةأكتوبر سابقا قسم امبابه جيزه', 'شارع السيده خديجه ناهيا كرداسه جيزه', 'شارع سعيد الجبان المنصورية مركز امبابة جيزه', 'شارع شركه الادويه مدينة دسوق قسم دسوق كفر شيخ', 'حارة فلسطين شياخة طلمبات عين شمس قسم عين شمس قاهرة', 'شارع عابدين الزقازيق البحرية قسم ثانى الزقازيق شرقية', 'امتداد شارع ابى بكر الصديق ابيس وخورشيد قسم ثان الرمل اسكندرية', 'شارع المركز مدينه ناصر ناصر بنى سويف', 'شارع كامل يوسف منشأة البكارى قسم الاهرام جيزه', 'شارع النحال الدقى قسم الدقى جيزه', 'شارع جامع الإمام شوبك بسطة مركز الزقازيق شرقية', 'حارة كوم القلعه قسم ثالث قسم الفيوم فيوم', 'شارع ابراهيم عبد الوهاب زاوية\xa0بلتان مركز طوخ قليوبية', 'حارة قنديل شياخة  مساكن الاميرية الشمالية قسم الزيتون قاهرة', 'شارع سيد عنبر شياخة عزبة الهجانة قسم اول مدينه نصر قاهرة', 'حارة الحاجب قسم ثان قسم ملوى منيا', 'شارع الترعه مدينة أشمون مركز اشمون منوفية', 'شارع رضا محمد بلتان مركز طوخ قليوبية', 'شارع النهضة شياخة فيصل قسم فيصل سويس', 'شارع مسجد الشهداء واحد العجمى البحرية قسم الدخيله اسكندرية', 'شارع ابراهيم الشريف برنشت العياط جيزه', 'شارع عمار بن ياسر باسوس مركز القناطر الخيريه قليوبية', 'شارع احمد عثمان الظهير الصحراوى العاشر من رمضان الظهير الصحراوى العاشر من رمضان شرقية', 'شارع الشهيد يحيي احمد عبد الملك مدينه العبور قسم العبور قليوبية', 'شارع كوبرى الوسط المسلمية مركز الزقازيق شرقية', 'شارع شوقى مبارك كفر\xa0مويس مركز بنها قليوبية', 'شارع عقبه بن نافع مدينة الفكرية ابو قرقاص منيا', 'شارع احمد عبد اللطيف سيدى بشر قبلى قسم المنتزة اسكندرية', 'شارع سبعة و سبعون مدينة رشيد رشيد بحيرة', 'شارع النقطه القديمة مسطرد قسم ثان شبرا الخيمه قليوبية', '